import { Geist, Geist_Mono, Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/navbar/NavBar";
import Providers from "../Components/themeProveder/Providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"   suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} min-h-full flex flex-col`}
      >
       
         <Providers  >
          
          <main className="max-w-11/12 mx-auto">
          <NavBar />

          {children}
          </main>
        </Providers>
      
      </body>
    </html>
  );
}
