import { Geist, Geist_Mono, Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/navbar/NavBar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} min-h-full flex flex-col`}
      >
        <NavBar />

        <main>{children}</main>
      </body>
    </html>
  );
}