import dns from "node:dns";

dns.setServers(["8.8.8.8", "8.8.4.4"]);
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/navbar/NavBar";
import Providers from "../Components/themeProveder/Providers";
import { ToastContainer } from "react-toastify";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} min-h-full flex flex-col`}
      >
        <Providers>
          <main className="max-w-98% mx-auto">
            <NavBar />
            <ToastContainer />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
